trigger:
  branches:
    include:
      - master
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndPushImage
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'tylereisenhauer/magehand-graph'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.SourceVersion)
                latest
              addPipelineData: false
              addBaseImageData: false