version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    logging:
      driver: none

  node:
    container_name: magehand-graph
    build:
      context: .
      dockerfile: Dockerfile
      args: [ "NODE_ENV=development" ]
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - mongodb

volumes:
  mongodata:

networks:
  default:
    external:
      name: magehand